services:
  _defaults:
    autowire: true
    autoconfigure: true

  GAYA\Taxonomy\:
    resource: '../Classes/*'

  # Events
  GAYA\Taxonomy\TaxonomyRegistry:
    tags:
      - name: event.listener
        identifier: 'gaya-taxonomy-registry'
        method: 'addTaxonomyDatabaseSchema'

  # DataProcessor
  GAYA\Taxonomy\DataProcessing\TaxonomyProcessor:
    shared: false
    tags:
      - name: 'data.processor'
        identifier: 'taxonomy'
