services:
  _defaults:
    autowire: true
    autoconfigure: true

  GAYA\Taxonomy\:
    resource: '../Classes/*'

  GAYA\Taxonomy\Utility\SiteConfigurationUtility:
    public: true
    shared: false

  # Events
  GAYA\Taxonomy\Database\SchemaGenerator:
    tags:
      - name: event.listener
        identifier: 'gaya-taxonomy-db-schema-generator'
        method: 'addTaxonomyDatabaseSchema'

  GAYA\Taxonomy\TsConfig\Loader:
    public: true
    shared: false
    tags:
      - name: event.listener
        identifier: 'gaya-taxonomy-page-ts-config'
        event: TYPO3\CMS\Core\TypoScript\IncludeTree\Event\ModifyLoadedPageTsConfigEvent
        method: 'addTaxonomyConfiguration'

  # DataProcessor
  GAYA\Taxonomy\DataProcessing\TaxonomyProcessor:
    shared: false
    tags:
      - name: 'data.processor'
        identifier: 'taxonomy'
